name: CI pipeline

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # install npm, install dependencies 
    - uses: bahmutov/npm-install@v1
      
    - name: Build project
      run: npx elm-app build

    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-southeast-2'
        SOURCE_DIR: 'build'      # optional: defaults to entire repository
